### ISSUE TITLE
0,0,0 submesh has more triangles than original model

### ISSUE THREAD

**Issue by darktable** [artnas/Unity-Plane-Mesh-Splitter#10]
I tried this out with a 112k triangle mesh that was generated by Google's Seurat tool. When splitting the mesh using a grid size of 120, I noticed that the 0,0,0 submesh has ~256k triangles, but all the other submeshes that I checked seem to have a correct number of triangles.

This is using the 1.1 unitypackage from releases in Unity 2021.3.8. [The seurat mesh unitypackage (~15mb)](https://drive.google.com/file/d/1MBpjrpRNNAjzDE37nayqY0E42cg6d31d/view?usp=sharing)

**Comment by darktable** [comment]
I think it may be every mesh has 3x the triangles, it was just most noticeable on the 0,0,0 submesh. These screenshots are from the snow terrain example in the project. The first image is from the submesh in the scene. The second image is a mesh exported from the same submesh game object using the FBX Exporter Unity package (`com.unity.formats.fbx`). There's probably a point where the stride is incorrect?

<img width="321" alt="Screen Shot 2022-09-30 at 10 44 48 PM" src="https://user-images.githubusercontent.com/585604/193394962-5f2e08b3-4cc9-46bc-9db0-98e6a5bb92d2.png">
<img width="308" alt="Screen Shot 2022-09-30 at 10 44 57 PM" src="https://user-images.githubusercontent.com/585604/193394968-cde763a3-8272-4367-97a9-e2c23c3c0c3e.png">

**Comment by darktable** [comment]
A workaround that's working for me is using Unity's FBX exporter on the split mesh. The exporter seems to combine redundant verts and/or triangles and the fbx output seems to have the correct number of triangles per submesh. 

p.s. Your mesh splitter has saved me a ton of time. Thanks!

**Comment by artnas** [comment]
Interesting. I can merge the vertices if that's the issue. Glad you found it useful, thanks for your contributions
