### ISSUE TITLE
Can't build game client due to MeshSplitController using editor-only properties

### ISSUE THREAD

**Issue by tomvoros** [artnas/Unity-Plane-Mesh-Splitter#15]
Some of the MeshRenderer properties copied in MeshSplitController.CreateChild() are available only in the editor and will break the build when used in a client.

Trying to build a client results in this error:

`Library\PackageCache\com.artnas.meshsplit@4e07ac9fe0\Runtime\Scripts\MeshSplitController.cs(121,33): error CS1061: 'MeshRenderer' does not contain a definition for 'receiveGI' and no accessible extension method 'receiveGI' accepting a first argument of type 'MeshRenderer' could be found (are you missing a using directive or an assembly reference?)`

**Comment by artnas** [comment]
I fixed the issue by wrapping the line in #if UNITY_EDITOR and updating package.json, unity should let you update the package through package manager.

Editing code directly on GitHub makes small changes convenient :D

**Comment by tomvoros** [comment]
Wow, you fixed it while I was having lunch! Certainly wasn't expecting that. 😄

I can confirm it's working now. Thanks!
