### ISSUE TITLE
I love you!

### ISSUE THREAD

**Issue by Alkanov** [artnas/Unity-Plane-Mesh-Splitter#3]
I am currently facing performance issues after doing a 8000x8000 map.. 350k tris 600k verts...

Used this, cut mesh to variable chunks of max 800 tris 2.6k verts... 

This made my month! Where is your Paypal?

**Comment by artnas** [comment]
Aww man, you've just made my day :D 

I'm so glad I could help. My paypal email is Arminator700@gmail.com. I'll drink a beer in your honour <3
