### ISSUE TITLE
I'm having trouble splitting my cube

### ISSUE THREAD

**Issue by browhattheheck1** [artnas/Unity-Plane-Mesh-Splitter#4]
I just created a cube and I want to split it into multiple cubes, but no matter how I change the settings in the controller it just cuts off the sides of the cube. Any help would be appreciated

**Comment by artnas** [comment]
> I just created a cube and I want to split it into multiple cubes, but no matter how I change the settings in the controller it just cuts off the sides of the cube. Any help would be appreciated

Make sure the geometry of the cube is in high enough resolution (triangles per cube face)

**Comment by browhattheheck1** [comment]
> 
> 
> > I just created a cube and I want to split it into multiple cubes, but no matter how I change the settings in the controller it just cuts off the sides of the cube. Any help would be appreciated
> 
> Make sure the geometry of the cube is in high enough resolution (triangles per cube face)

How would I check that? I'm just spawning in the default cube in unity. I got it to not just cut off the sides now (the original reasoning being I had the values of size set to x- 200 y-5 z-200), but now it will not cut the cube at all. When I hit create submeshes it creates one submesh which is the whole cube

**Comment by artnas** [comment]
> > > I just created a cube and I want to split it into multiple cubes, but no matter how I change the settings in the controller it just cuts off the sides of the cube. Any help would be appreciated
> > 
> > 
> > Make sure the geometry of the cube is in high enough resolution (triangles per cube face)
> 
> How would I check that? I'm just spawning in the default cube in unity. I got it to not just cut off the sides now (the original reasoning being I had the values of size set to x- 200 y-5 z-200), but now it will not cut the cube at all. When I hit create submeshes it creates one submesh which is the whole cube

The default cube in Unity is a very simple mesh, it only uses 2 triangles per cube face. This tool is designed to split large, more complex geometry into sections.
