### ISSUE TITLE
Splitting meshes with a larger grid size

### ISSUE THREAD

**Issue by cbanwell** [artnas/Unity-Plane-Mesh-Splitter#6]
Just having a play with the asset, we have extremly large meshes 2-5kmsq, having a play with the grid size I edited the code to enable grid sizes > 256 to be used, but what I find is that the slit then seems to miss chunks out, just wondering if the original 64 grid size limit is a known limitation and if so what the reason is?

Btw. seems to work fine if grid size is less than 64.

**Comment by artnas** [comment]
The 64 grid size limit is just an arbitrary number - it should work well with higher values. Perhaps its some sort of a float rounding error?

**Comment by artnas** [comment]
> Just having a play with the asset, we have extremly large meshes 2-5kmsq, having a play with the grid size I edited the code to enable grid sizes > 256 to be used, but what I find is that the slit then seems to miss chunks out, just wondering if the original 64 grid size limit is a known limitation and if so what the reason is?
> 
> Btw. seems to work fine if grid size is less than 64.

Hey I've recently picked up this project again and did you ever fix the error? If you have a mesh which is causing issues then feel free to email it to me or attach it here - I'll try and see what's going on.

**Comment by cbanwell** [comment]
Sure, I can’t upload one for all to see, anyway to get it to you privately, my email is: ***@***.***(dot)co(dot)uk

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by artnas** [comment]
> Sure, I can’t upload one for all to see, anyway to get it to you privately, my email is: ***@***.***(dot)co(dot)uk

I think github has hidden the email - you can see my email on my profile on github

**Comment by cbanwell** [comment]
yep lol, thanks for investigating this in advance.

Just sent you a wetransfer
