### ISSUE TITLE
Can't split planet into chunks.

### ISSUE THREAD

**Issue by Panicat** [artnas/Unity-Plane-Mesh-Splitter#9]
Hello. I can't split a pretty complex planet mesh with the Mesh Split Controller script.
I'll be posting a lot of images to hopefully showcase the issue to someone who understands how this works.

An example of a planet I want to split:

![image](https://user-images.githubusercontent.com/59578148/190860167-b0b1cf08-018d-4e80-a175-31b077112df0.png)

Results with grid size 0.1

![image](https://user-images.githubusercontent.com/59578148/190860198-eb0b4cbf-3a3a-4cce-9fe2-8f70c39d8f30.png)

Results with grid size 1

![image](https://user-images.githubusercontent.com/59578148/190860214-7b9fbc65-cce6-4981-a3e0-f8e831a41984.png)

Grid size 2

![image](https://user-images.githubusercontent.com/59578148/190860231-193d4421-234b-4f17-8f89-b7b3fa1c1b80.png)

Anything over 2 only leaves one submesh, a piece up top.

![image](https://user-images.githubusercontent.com/59578148/190860252-99f38513-82cb-41ef-bad9-3cee304592e2.png)

Example trying to cover the entire planet with the grid size:

![image](https://user-images.githubusercontent.com/59578148/190860342-cde1fe6c-68bc-4f8c-9a02-ce289e09335a.png)
![image](https://user-images.githubusercontent.com/59578148/190860347-1fa74946-9140-402a-be90-91abd9fc4f32.png)
![image](https://user-images.githubusercontent.com/59578148/190860409-96b046fa-8d13-4261-ba71-5e5b1bac5dba.png)

And making it small compared to the planet:

![image](https://user-images.githubusercontent.com/59578148/190860443-8bf92191-7b90-4f3c-bb5e-e8f6d66cbe13.png)
![image](https://user-images.githubusercontent.com/59578148/190860452-b603a89d-020d-4035-b637-01fcd05f8a7a.png)
![image](https://user-images.githubusercontent.com/59578148/190860459-ea75b188-b5bf-4ee6-a2d1-237aeedde30a.png)

Nothing seems to work. I've tried it in playmode, too.
Any help would be greatly appreciated. This seems like just the thing for what I'm trying to do and I'm sad it isn't working as intended!

**Comment by artnas** [comment]
Interesting. Any errors in the console? Can you provide the mesh so I can see whats up?

**Comment by Panicat** [comment]
Nothing in the console.

The mesh is generated inside Unity using [Sebastian Lague's celestial body generation system](https://github.com/SebLague/Solar-System), which might be the cause? But I don't get why it would have to be a mesh that was imported into Unity for it to work.
Mesh filter and renderer are present, as well as mesh collider.

However, it seems that the grid gizmos don't even change when changing the grid scale. With a simple tree mesh I tried in another project, it seems to work and that happens when I change the scale.

**Comment by artnas** [comment]
It might be an issue with how the mesh is generated (the structure of its data). I checked out the code generating the planet mesh and it doesn't seem to do anything out of the ordinary, maybe except for using an uv channel for custom data. You could try exporting the mesh from unity (apparently its built in functionality now: https://docs.unity3d.com/Packages/com.unity.formats.fbx@2.0/manual/exporting.html), import it back and then try to split the imported fbx mesh.

**Comment by artnas** [comment]
I pushed an update today, you can see if it helps.

**Comment by Panicat** [comment]
Uh, with the new version the console is full of errors just when importing for me.

![image](https://user-images.githubusercontent.com/59578148/190893578-24d8bd3a-b2a4-479f-bb6b-bc3d3c5f4065.png)

Trying to attach the controller to an object crashes Unity.

**Comment by Panicat** [comment]
Exporting and importing breaks mesh colours and the grid is now a single cube made of lots of lines. (Old version)

![image](https://user-images.githubusercontent.com/59578148/190893909-4e40b862-e2cd-4d47-bc8d-2f7aeb16bcab.png)
![image](https://user-images.githubusercontent.com/59578148/190893929-e8f3d322-902a-4a03-9569-d3441ef70457.png)

![image](https://user-images.githubusercontent.com/59578148/190893944-59f1b925-03b8-47f9-b72d-d8b8c38d0e0d.png)
![image](https://user-images.githubusercontent.com/59578148/190893949-2e9e563a-6e60-4b8d-a1b1-a95064539ed2.png)

**Comment by Panicat** [comment]
Okay so, with a lower planet resolution (LOD) it seems to work

![image](https://user-images.githubusercontent.com/59578148/190895137-284d9279-0f31-4730-8d9b-a8acde5ab181.png)

So the issue must be the amount of vertices/triangles with the resolution I was using before. Would it be easy to fix this? Is there a limit to how many vertices or triangles my mesh should have?

Even with this, there seems to be a ton of deviation to the size of chunks, not sure if that's how it's meant to be or not.

![image](https://user-images.githubusercontent.com/59578148/190895234-937567b0-4869-4a2a-8a7e-6857d155da37.png)
![image](https://user-images.githubusercontent.com/59578148/190895236-f05c6bb8-14d6-41f5-aab1-849ac5de42c3.png)

**Comment by artnas** [comment]
> Uh, with the new version the console is full of errors just when importing for me.
> 
> ![image](https://user-images.githubusercontent.com/59578148/190893578-24d8bd3a-b2a4-479f-bb6b-bc3d3c5f4065.png)
> 
> Trying to attach the controller to an object crashes Unity.

Are you using an old version of unity? The new version uses the latest unity 2021.3.10

Try removing the old package scripts before importing new ones

**Comment by artnas** [comment]
> Okay so, with a lower planet resolution (LOD) it seems to work
> 
> ![image](https://user-images.githubusercontent.com/59578148/190895137-284d9279-0f31-4730-8d9b-a8acde5ab181.png)
> 
> So the issue must be the amount of vertices/triangles with the resolution I was using before. Would it be easy to fix this? Is there a limit to how many vertices or triangles my mesh should have?
> 
> Even with this, there seems to be a ton of deviation to the size of chunks, not sure if that's how it's meant to be or not.
> 
> ![image](https://user-images.githubusercontent.com/59578148/190895234-937567b0-4869-4a2a-8a7e-6857d155da37.png)
> ![image](https://user-images.githubusercontent.com/59578148/190895236-f05c6bb8-14d6-41f5-aab1-849ac5de42c3.png)

The vertices are grouped by closest grid coordinates, so the chunk size variance is expected (some grid coordinates can even contain just one triangle).

The amount of vertices shouldnt be a problem in any of the versions

**Comment by Panicat** [comment]
But, it's related to the quality of the planet, seeing as the lower ones work. I don't know..

**Comment by artnas** [comment]
Hey, did you try the new versions? You can now install it with UPM

**Comment by Panicat** [comment]
> Hey, did you try the new versions? You can now install it with UPM

Yes I have tried 1.1, and now just reinstalled it for Unity 2021.3.11 but it still has errors
This isn't completed, my issue isn't fixed here?

![image](https://user-images.githubusercontent.com/59578148/196692738-c98c5200-9b29-4332-81f9-7a01c41e7281.png)
![image](https://user-images.githubusercontent.com/59578148/196692772-cc205eb8-8f00-4e01-9e66-a499e6cfd574.png)
![image](https://user-images.githubusercontent.com/59578148/196692975-048bf2ea-e27b-4799-9c80-7664c7a7d371.png)

**Comment by artnas** [comment]
You need to install it as an UPM package so it automatically resolves the package dependencies (half4 is from Unity.Mathematics etc). Here's how you can do it: https://github.com/artnas/Unity-Plane-Mesh-Splitter#installation

**Comment by Panicat** [comment]
I had errors with the UPM import asking me to install Git, which I did, I would expect Unity to just install the unity package without this being required but okay. It works! Thanks. It doesn't seem to affect performance as much as I expected (minimally in fact) even with just a single planet being mostly culled at different grid sizes. But pretty cool

**Comment by artnas** [comment]
Looks like git is required when downloading a github repo.

You should try occlusion culling to hide the back side of the planet. As long as the planet is static it shouldn't be a problem
